spring:
  docker:
    compose:
      enabled: false
  datasource:
    url: jdbc:postgresql://127.0.0.1:5433/nasastealer
    username: po-user
    password: po-user
  # JPA/Hibernate properties
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

#Logging
logging:
  level:
    root: INFO
    org:
      springframework:
        transaction: DEBUG
        orm:
          jpa: DEBUG

nasa:
  api-key: cHNew3scYGUY2LCuFVQb3w6eAAddoyBBH6RAChhF
  host: https://api.nasa.gov/mars-photos/api/v1


