spring:
  docker:
    compose:
      enabled: false
  datasource:
    url: jdbc:postgresql://127.0.0.1:5433/nasastealer
    username: po-user
    password: po-user
  # JPA/Hibernate properties
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
    properties:
      jakarta:
        persistence:
          sharedCache:
            mode: ENABLE_SELECTIVE
      hibernate:
        transaction:
          jta:
            enable: false
        cache:
          use_second_level_cache: true
          use_query_cache: true
          region:
            factory_class: infinispan
          infinispan:
            statistics:
              enabled: true
            #file_store:
            #  location: 'infinispan/cache-store'
            # Force using local configuration when only using a single node.
            # Otherwise a clustered configuration is loaded.
            cfg: org/infinispan/hibernate/cache/commons/builder/infinispan-configs-local.xml
    open-in-view: false

#Logging
logging:
  level:
    root: INFO
    org:
      springframework:
        transaction: DEBUG
        orm:
          jpa: DEBUG

nasa:
  api-key: ${NASA_API_KEY}
  host: https://api.nasa.gov/mars-photos/api/v1


