version: '3.8'
services:
  postgres:
    container_name: postgres-15
    image: 'postgres:15.5'
    restart: always
    environment:
      - 'POSTGRES_DB=bobocode'
      - 'POSTGRES_PASSWORD=po-user'
      - 'POSTGRES_USER=po-user'
    volumes:
      - ./docker-entrypoint-initdb.d/:/docker-entrypoint-initdb.d/
    ports:
      - "5433:5432"
